### ISSUE TITLE
I keep getting this error when running the bot...

### ISSUE THREAD

**Issue by derekisbusy** [phracker/zookeeper#2]
Traceback (most recent call last):
  File "./zookeeper.py", line 794, in <module>
    bot.start() # Start the IRC bot
  File "/root/zookeeper/ircbot.py", line 247, in start
    SimpleIRCClient.start(self)
  File "/root/zookeeper/irclib.py", line 1114, in start
    self.ircobj.process_forever()
  File "/root/zookeeper/irclib.py", line 229, in process_forever
    self.process_once(timeout)
  File "/root/zookeeper/irclib.py", line 214, in process_once
    self.process_data(i)
  File "/root/zookeeper/irclib.py", line 183, in process_data
    c.process_data()
  File "/root/zookeeper/irclib.py", line 581, in process_data
    self._handle_event(Event(command, prefix, target, [m]))
  File "/root/zookeeper/irclib.py", line 604, in _handle_event
    self.irclibobj._handle_event(self, event)
  File "/root/zookeeper/irclib.py", line 325, in _handle_event
    if handler[1](connection, event) == "NO MORE":
  File "/root/zookeeper/irclib.py", line 1049, in _dispatcher
    getattr(self, m)(c, e)
  File "./zookeeper.py", line 558, in on_pubmsg
    inf = getUserInfo(sent_user)
  File "./zookeeper.py", line 253, in getUserInfo
    SQL = mysql()
  File "./zookeeper.py", line 97, in __init__
    self.sql = MySQLdb.connect(host = MySQL_host, user = MySQL_user, passwd = MySQL_passwd, db = MySQL_db, reconnect = 1)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/**init**.py", line 81, in Connect
    return Connection(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in **init**
    super(Connection, self).**init**(_args, *_kwargs2)
TypeError: 'reconnect' is an invalid keyword argument for this function

**Comment by derekisbusy** [comment]
I fixed this by removing the reconnect param from the MySQLdb.connect() statement on line 97 or zookeeper.py.
